name: alpha job 
on: 
   workflow_call:
    inputs:
        color:
           required: true
           type: string
    secrets:
        username:
           required: true
                 

jobs:
   alpha-first-job:
     runs-on: ubuntu-latest
     steps:
       - name: chekout
         uses: actions/checkout@v3

       - name: list files
         run: |
            ls -la  
            pwd

       - name: print msg
         run: | 
             echo ${{ inputs.color}}
             echo ${{ secrets.username}}

       - name: run python script
         run: python abc.py    
               